### ISSUE TITLE
use of undeclared identifier 'assert'

### ISSUE THREAD

**Issue by YaroShkvorets** [turnpike/blanc#5]
When trying to compile one of the contracts with blanc++ I get this error:

```
include/atomicassets/base58.hpp:107:9: error: use of undeclared identifier 'assert'
        assert(carry == 0);
```

Works fine when compiling with eosio-cpp though.

Right now I have to add a define before any includes to bypass it

```
#define assert(condition) ((void)0)
```

**Comment by conr2d** [comment]
I analyzed this issue, but found this is not a bug. eosio.cdt uses libcxx-9, but blanc is shipped with libcxx-11.
In libcxx-9, C++ header `<memory>` includes `<cassert>` [[ref]](https://github.com/EOSIO/libcxx/blob/dd2d7b0f/include/memory#L665), but in the newer libcxx-11, `<cassert>` inclusion is removed. [[ref]](https://github.com/turnpike/libcxx/blob/5c7f184a/include/memory#L666).

In atomicassets case, `assert` is included by accident with eosio.cdt, but adding `#include <cassert>` to base58.hpp is a correct way to fix this.

**Comment by YaroShkvorets** [comment]
Great, thanks.
